### ISSUE TITLE
A question about the training dataset

### ISSUE THREAD

**Issue by babymetal287** [epelofske-student/CTC#1]
Hi I am interested in using the training dataset but I have a trouble to download the file from next cloud. It requires me to login in a nextcloud account before the downloading. I'd like to know whether it is because the download link is not available now. Or there are any other ways that I can download the training dataset (such as google drive)?. Thank you.

**Comment by epelofske-student** [comment]
Indeed, the next cloud link has gone dead - I have put the data up on Zenodo: https://zenodo.org/records/10655913
